name = "tbd"
license = "MIT"
licenselink = "https://github.com/daturkel/blank/blob/master/LICENSE"
description = "Minimal blog theme for Hugo, forked from Vimux's blank theme"
homepage = "https://github.com/daturkel/blank/"
tags = ["blog", "plain", "blank", "starter"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "daturkel"
  homepage = "https://github.com/daturkel"
